
desc orders;
desc customers;
desc sellers;
desc products;
desc categories;
desc order_items;
desc payments;
desc reviews;

-- Feature 1: Customer analytics (7 queries)
select count(cust_id) as total_customers from customers;
select count(order_id) as order_id from orders; 
select sum(total_amt) as tot_amt from orders;
select avg(total_amt) as avg_amt from orders;

select (select count(cust_id) from customers) as tot_cus, (select count(order_id) from orders) as tot_ord,
(select sum(total_amt) from orders) as tot_amt, (select avg(total_amt) from orders ) as avg_amt ;

-- 1. Find which customers are placing the most orders.
select customers.cust_id, customers.name, orders.count from customers join
(select cust_id ,count(order_id) as count from orders group by cust_id order by count desc) as orders 
where customers.cust_id = orders.cust_id ;

-- 2. Customers who have never placed an order
select customers.cust_id, customers.name, customers.city from customers join
(select cust_id,count(order_id) from orders group by cust_id having count(order_id) = 0) as orders
where customers.cust_id = orders.cust_id;

-- 3.How much has each customer spent in total?
select a.cust_id, a.name, b.spent from customers as a join
(select cust_id, sum(total_amt)as spent from orders group by cust_id) as b
where a.cust_id = b.cust_id;

-- 4. Which customers have spent more than ₹10,000 in total?
select a.cust_id, a.name, b.spent from customers as a join
(select cust_id, sum(total_amt)as spent from orders group by cust_id) as b
where a.cust_id = b.cust_id and spent > 10000;

-- 5.How many customers are registered in each city?
select city, count(cust_id) as no_of_customers from customers group by city order by no_of_customers desc;

-- 6.Customers who have placed more than one order.
 select customers.cust_id, customers.name, orders.count from customers join
(select cust_id ,count(order_id) as count from orders group by cust_id order by count desc) as orders 
where customers.cust_id = orders.cust_id and orders.count>1;

-- 7.Customer name, number of orders, and total amount spent.
select a.cust_id, a.name ,b.count, b.tamt from customers as a join
(select cust_id,count(order_id) as count, sum(total_amt) as tamt from orders group by cust_id order by cust_id)as b
where b.cust_id = a.cust_id;

-- Feature 2: Product and category analysis ( 6 queries)

-- 1. Product name, category, seller, price, and stock.
select c.prod_id, c.prod_name,c.cate_name,sellers.seller_name,c.price from sellers join
(select b.prod_id, b.prod_name,a.cate_name, b.price, b.seller_id  from categories as a join
(select prod_id, Prod_name ,seller_id, price, stock, cate_id from products) as b
where a.cate_id = b.cate_id order by prod_id) as c where c.seller_id = sellers.seller_id order by prod_id;

SELECT p.prod_id, p.prod_name, c.cate_name, s.seller_name, p.price,p.stock FROM products p JOIN 
categories c ON p.cate_id = c.cate_id
JOIN sellers s ON p.seller_id = s.seller_id
ORDER BY p.prod_id;

-- 2.How many units were sold from each product category?
select c.cate_name, sum(a.quantity)as units_sold from order_items as a 
Join Products as b on a.prod_id = b.prod_id 
join categories as c on c.cate_id = b.cate_id group by c.cate_name ;

-- 3. Find the total sales revenue generated by each product category.
select c.cate_name, sum(a.price)as price from order_items as a 
Join Products as b on a.prod_id = b.prod_id 
join categories as c on c.cate_id = b.cate_id group by c.cate_name ;

-- 4.Find products whose total sales revenue is greater than the average sales revenue of all products.
select a.prod_id, b.prod_name, a.price from products as b join 
(select prod_id, sum(price) as price from order_items  where price >
(select avg(b.price) as avg_sales from 
(select prod_id, sum(price) as price from order_items group by prod_id)as b) group by prod_id)as a 
where a.prod_id = b.prod_id;

-- 5. The application should identify products that have low stock, so the business can restock them.
select prod_id, prod_name, stock from products where stock <20;

   /*6.Find the average product price for each category, and show only categories whose average product 
price is greater than ₹2,000.*/
select a.cate_id,a.cate_name,b.avg_product_price from categories as a join
(select cate_id, sum(price)/count(prod_id) as avg_product_price from products group by cate_id) as b 
where a.cate_id = b.cate_id and b.avg_product_price > 2000 order by a.cate_id;

-- Feature 3: Sales ans Order Analytics (7 queries)

-- 1. The application should show a summary of orders based on their status.
select status,count(order_id) as order_count from orders group by status order by status;

-- 2.Find the total sales amount for each order status.
select status, sum(total_amt) as Total_sales from orders group by status;

-- 3.Find how many orders were paid using each payment method, and how much money was associated with each method.
select c.pay_method, count(Order_id) as order_count, sum(total_amt) as total_sales from 
(select a.order_id, b.pay_method, a.total_amt from orders as a join payments as b where a.order_id = b.order_id) as c 
group by c.pay_method;

-- 4. Classify each order based on its total amount
select order_id, total_amt, case
when total_amt < 2000 then "Low value"
when total_amt >= 2000 and total_amt <= 10000 then "Medium Value"
when total_amt >10000 then "High value"
end as order_Type from orders; 

-- 5. Count how many orders fall into Low, Medium, and High value categories.
select temp.order_type, count(order_id) as order_count from (select order_id, total_amt, case
when total_amt < 2000 then "Low value"
when total_amt >= 2000 and total_amt <= 10000 then "Medium Value"
when total_amt >10000 then "High value"
end as order_Type from orders) as Temp group by temp.order_type; 

-- 6.Show the total sales for each month.
select year (order_date) as Year, month(order_date) as Month, sum(total_amt) as Total_sales from orders 
group by month(order_date), year(order_date);

select date_format(order_date,"%y-%m") as Mon_yr, sum(total_amt) as total_sales from orders 
group by date_format(order_date,"%y-%m");

-- 7.Show how many payments are completed and how many are refunded.
select pay_status, count(order_id) as Payment_count from payments group by pay_status;

-- Feature 4;: Customer Behavior & ranking (10 queries)

-- 1.Rank all customers according to their total spending.
select q.* ,
rank() over(order by total_spend desc) as rnk from (select b.cust_id, a.name, b.total_spend from customers as a join
(select cust_id, sum(total_amt) as total_spend from orders Group by cust_id) as b 
where a.cust_id = b.cust_id) as q;

-- 2.Rank customers based on their total spending, but separately within each city.
select a.*, 
rank() over(partition by city  order by total_spent desc) as rnk from 
(select a.cust_id, a.name, a.city, b.total_spent from customers as a 
join (select cust_id, sum(total_amt) as total_spent from orders group by cust_id) as b where a.cust_id = b.cust_id) as a;

-- 3.Rank customers by total spending, but if two customers have the same spending, assign them the same rank.
select q.* ,
rank() over(order by total_spend desc) as rnk from (select b.cust_id, a.name, b.total_spend from customers as a join
(select cust_id, sum(total_amt) as total_spend from orders Group by cust_id) as b 
where a.cust_id = b.cust_id) as q;

-- 4.Rank customers by total spending, but don't leave gaps after ties.
select q.* ,
dense_rank() over(order by total_spend desc) as rnk from (select b.cust_id, a.name, b.total_spend from customers as a join
(select cust_id, sum(total_amt) as total_spend from orders Group by cust_id) as b 
where a.cust_id = b.cust_id) as q;

-- 5.Give every customer a unique position based on total spending. 
-- Even if two customers have exactly the same spending, they must receive different numbers
select a.*, row_number() over(order by total_spent desc)as row_no from 
(select a.name, b.total_spent from customers as a join 
(select cust_id, sum(total_amt) as total_spent from orders group by cust_id)as b where a.cust_id = b.cust_id) as a;

-- 6.Show the top 3 customers based on total spending
select w.* from (select q.*, 
rank() over(Order by total_spent desc)as rnk from
(select a.cust_id , a.name , b.total_spent from customers as a join
(select cust_id, sum(total_amt) as total_spent from orders group by cust_id) as b
 where a.cust_id = b.cust_id) as q )as w where w.rnk <4;
 
 -- 7.For each city, show the highest-spending customer and their total spending.
select w.* from (select q.*,
rank()over(partition by city order by total_spent desc) as rnk from
(select a.cust_id, a.city, a.name , b.total_spent from customers as a join
(select cust_id, sum(total_amt) as total_spent from orders group by cust_id)as b where a.cust_id = b.cust_id) as q) as w 
where rnk <2;

-- 8.Show each customer's total spending along with the spending of the customer 
-- immediately above them in the overall spending ranking.
select b.*, 
lag(total_spent)over(order by total_spent desc) as prev_spent from 
(select a.cust_id, a.name , b.total_spent from customers as a join
(select cust_id, sum(total_amt) as total_spent from orders group by cust_id)as b where a.cust_id = b.cust_id) as b;

-- 9.Show each customer's spending and the spending of the customer immediately below them in the spending ranking.
select b.*, 
lead(total_spent)over(order by total_spent desc) as prev_spent from 
(select a.cust_id, a.name , b.total_spent from customers as a join
(select cust_id, sum(total_amt) as total_spent from orders group by cust_id)as b where a.cust_id = b.cust_id) as b;

-- 10.For each customer, show their total spending and the percentage of total company sales contributed by that customer.
select q.name, (q.total_spent/q.total_com_sales)*100 as sales_percentage from
(select a.name, b.total_spent, b.total_com_sales from customers as a join 
(select cust_id, sum(total_amt) as total_spent,(select sum(total_amt)  from orders) as total_com_sales from 
orders group by cust_id) as b where a.cust_id = b.cust_id) as q;

-- Feature 5: Purchase Trends (7 Queries)

-- 1.Find the total sales for each month, along with the number of orders placed in that month.
select date_format(order_date, "%y-%m") as year_mon, count(order_id) as order_count, sum(total_amt) as Total_sales from 
orders group by date_format(order_date, "%y-%m");

-- 2.Find the month with the highest total sales.
create view view1 as  select date_format(order_date, "%y-%m") as year_mon, count(order_id) as order_count, 
sum(total_amt) as Total_sales from orders group by date_format(order_date, "%y-%m");
select * from view1  where view1.total_sales = (select max(total_sales) from view1);

-- 3.Show each month's sales along with the previous month's sales.
create view a as select date_format(order_date,"%y-%m") as year_mon, sum(total_amt) as total_sales from 
orders group by date_format(order_date,"%y-%m");

select a.*, lag(a.total_sales) over(order by a.year_mon) as previous_month_sales from a;

-- 4.Calculate the month-over-month percentage change in sales.
select b.*,((b.total_sales - b.prev_mon_sales)*100/prev_mon_sales) as mon_mon_percent from
(select a.*, lag(a.total_sales) over(order by a.year_mon) as prev_mon_sales from a)as b;

-- 5.Find the average monthly sales and show only the months whose sales are above the average monthly sales.
drop view s1;
create view s1 as select date_format(order_date,"%y-%m") as YR_MN,sum(total_amt) as total_sales 
from orders group by date_format(order_date,"%y-%m");
select * from s1;
select * from s1 where s1.total_sales > (select avg(s1.total_sales) from s1) ;

-- 6.Find the month with the highest number of orders and display the month and order count.
select * from (select date_format(order_date,"%y-%m") as Yr_mn, count(order_id) as order_count from 
orders group by date_format(order_date,"%y-%m"))as A where A.order_count = (select Max(b.order_count)from 
(select date_format(order_date,"%y-%m") as Yr_mn, count(order_id) as order_count from 
orders group by date_format(order_date,"%y-%m"))as b);

-- 7.For each month, show total sales and classify the month as High Sales, Medium Sales, or Low Sales.
select * , case
when a.total_sales > 50000 then "High Sales"
when a.total_sales >=20000 and a.total_sales <=50000 then "Medium sales"
Else "low sales" end as Sales_type
from (select date_format(order_date,"%y-%m") as Yr_mn, sum(total_amt) as total_sales from
orders group by date_format(order_date,"%y-%m")) as A;

-- Feature 6: Reviews and seller Analytics ( 6 Queries)

-- 1.For each product, show the product name, number of reviews, and average rating.
select a.prod_name,b.no_of_ratings, b.review from products as a join
(select prod_id, count(rating) as No_of_ratings, avg(rating) as review from reviews group by prod_id) as b 
where a.prod_id = b.prod_id;

-- 2.For each category, find the average product rating and number of reviews.
select q.cate_name, count(rating)as review_count, avg(rating) as avg_rating from 
(select d.cate_name, c.cate_id, c.rating from categories as d join
(select a.prod_id, a.cate_id, b.rating from products as a join reviews as b where a.prod_id = b.prod_id) as c 
where c.cate_id = d.cate_id) as q group by q.cate_name ;

-- 3.For each seller, show the seller name, number of products they sell, and total units sold.
select q. seller_name,  count(distinct prod_name) as prod_count, sum(quantity) as unit_sold from
(select a.seller_id, a.seller_name, a.prod_id, a.prod_name, c.Quantity from 
(select a.seller_id, b.seller_name, a.prod_id, a.prod_name from products as a join sellers as b 
where a.seller_id = b.seller_id) as a join order_items as c where a.prod_id = c.prod_id) as q group by q.seller_name;

-- 4.For each seller, calculate the total revenue generated by their products.
select w.seller_name, sum(quantity * price) as total_rev from
 (select q.seller_id, q.seller_name, q.prod_id, q.prod_name,a.quantity, a.price from  
(select a.seller_id, a.seller_name, b.prod_id,b.prod_name from sellers as a join products as b
where a.seller_id = b.seller_id) as q join order_items as a where q.prod_id = a.prod_id)as w group by seller_id;

-- 5.For each seller, show the seller name and average rating of all products sold by that seller.
select q.seller_name, avg(rating) as avg_rating from 
(select a.seller_id,a.seller_name, reviews.rating from 
(select a.seller_id, a.seller_name, b.prod_id,b.prod_name from sellers as a join products as b
where a.seller_id = b.seller_id) as a join reviews where a.prod_id = reviews.prod_id) as q group by seller_name;

-- 6. Find products whose average rating is greater than the overall average rating of all reviews.
create view s2 as (select q.prod_name, avg(rating) as rating from 
(select a.prod_id,a.prod_name, b.rating from products as a join reviews as b where a.prod_id=b.prod_id) as q
group by prod_id) ;

select * from s2 where s2.rating > (select avg(s2.rating) from s2) order by rating desc;

-- Feature 7: Advanced Business Queries (7 Queries)

-- 1.Find customers who have purchased products from at least 2 different categories.
create view s3 as select w.*, a.cate_name from (select q.*, a.cate_id from(select a.cust_id, a.name,a.order_id, b.prod_id from 
(select a.name, a.cust_id, b.order_id from customers as a join orders as b where a.cust_id = b.cust_id)as a join 
order_items as b where a.order_id = b.order_id) as q join products as a where a.prod_id =q.prod_id ) as w join categories as a
where a.cate_id = w.cate_id;
select * from s3;

select s3.cust_id, s3.name  from s3 group by s3.cust_id having Count(distinct s3.cate_name)>=2;

-- 2.Find customers who have spent more than ₹10,000 across products belonging to at least 2 different categories.
select a.* from (select a.*, b.total_spent from
(select s3.cust_id, s3.name  from s3 group by s3.cust_id having Count(distinct s3.cate_name)>=2) as a join
(select cust_id, sum(total_amt) as total_spent from orders group by cust_id) as b where a.cust_id = b.cust_id) as a 
where a.total_spent > 10000;

-- 3.Find customers who have purchased every product category available in the database.
select s3.name, count( distinct cate_name) as category_count from s3 
group by s3.name having count( distinct cate_name) = (select count(cate_id) from categories);

-- 4.Find products that have never been ordered.
select a.prod_id, a.prod_name from products as a left join order_items as b on a.prod_id = b.prod_id 
where b.prod_id is null; 

-- 5.Find the seller whose products generated the highest total revenue.
create view s5 as(select a.*, b.seller_name from(select a.* , b.seller_id from
(select prod_id, sum(quantity*price) as total_spent from order_items group by prod_id) as a join products as b 
where a.prod_id = b.prod_id) as a join sellers as b where a.seller_id = b.seller_id); 
select * from s5;

select a.* from(select s5.seller_name, sum(s5.total_spent) as total_rev from s5 
group by s5.seller_name) as a where a.total_rev = (select max(a.total_rev) from (select s5.seller_name, sum(s5.total_spent) as total_rev from s5 
group by s5.seller_name) as a );

-- 6. Find customers who have placed orders but have never submitted a review.
select a.cust_id, a.name from customers as a join
(select a.cust_id  from orders  as a left join reviews as b on a.cust_id = b.cust_id where b.cust_id is null)as b 
on a.cust_id = b.cust_id;

-- 7. Find the top 3 products by total revenue, showing product name, units sold, and total revenue.
create view s6 as (select a.*, b.prod_name from
(select prod_id, sum(quantity) as units_sold, sum(quantity *price) as tota_revenue from order_items group by prod_id)as a
join products as b on a.prod_id= b.prod_id) ; 

select a.prod_name, a.units_sold,a.tota_revenue from 
(select s6.*, rank() over(order by s6.tota_revenue desc) as rnk from s6)as a where rnk < 4;